#include <iostream>
#include <set>
#include <map>
#include <vector>
#include <string>

#include "expr_tokens.h"
#include "expr_rules.h"


/// <summary>
/// Initializes a Tokenizer with a set of token types and their corresponding regular expressions for parsing assembly-like language.
/// </summary>
Tokenizer tokenizer({
    { COMMENT,      R"(\;[^\n]*)" },
    { DECNUM,       R"(\d+)" },
    { CHAR,         R"((\'.\')|(\".\"))" },
    { OCTNUM,       R"((?:0[0-7]+)|(?:0[oO][0-7]+)|(?:[oO][0-7]+)|(?:&[0-7]+))" },
    { HEXNUM,       R"(\$([A-F0-9]+[ \t]+)+[A-F0-9]+|\$([A-F0-9]+))" },
    { BINNUM,       R"(%([0-1]+[ \t]+)+[0-1]+|%([0-1])+)" },
    { TEXT,         R"(\'[^']*\'|\"[^\"]*\")" },
    { LOGICAL_AND,  R"(\&\&)" },
    { LOGICAL_OR,   R"(\|\|)" },
    { LT,           R"(\<)" },
    { GT,           R"(\>)" },
    { LE,           R"(\<=)" },
    { GE,           R"(\>=)" },
    { DEQUAL,       R"(\=\=)" },
    { NOTEQUAL,     R"((\!\=)|(\<\>))" },
    { PLUS,         R"(\+)" },
    { MINUS,        R"(\-)" },
    { EQUAL,        R"(\=)" },
    { COMMA,        R"(,)" },
    { COLAN,        R"(\:)" },
    { POUND,        R"(\#)" },
    { MUL,          R"(\*)" },
    { DIV,          R"(\/)" },
    { MOD,          R"(\%)" },
    { BIT_AND,      R"(\&)" },
    { BIT_OR,       R"(\|)" },
    { ONESCOMP,     R"(\~)" },
    { SLEFT,        R"(<<)" },
    { SRIGHT,       R"(>>)" },
    { LPAREN,       R"(\()" },
    { RPAREN,       R"(\))" },
    { AT,           R"(\@)" },
    { WS,           R"([ \t]+)" },
    { ORA,          R"(\bORA\b)"  },
    { AND,          R"(\bAND\b)"  },
    { EOR,          R"(\bEOR\b)"  },
    { ADC,          R"(\bADC\b)"  },
    { SBC,          R"(\bSBC\b)"  },
    { CMP,          R"(\bCMP\b)"  },
    { CPX,          R"(\bCPX\b)"  },
    { CPY,          R"(\bCPY\b)"  },
    { DEC,          R"(\bDEC\b)"  },
    { DEX,          R"(\bDEX\b)"  },
    { DEY,          R"(\bDEY\b)"  },
    { INC,          R"(\bINC\b)"  },
    { INX,          R"(\bINX\b)"  },
    { INY,          R"(\bINY\b)"  },
    { ASL,          R"(\bASL\b)"  },
    { ROL,          R"(\bROL\b)"  },
    { LSR,          R"(\bLSR\b)"  },
    { ROR,          R"(\bROR\b)"  },
    { LDA,          R"(\bLDA\b)"  },
    { STA,          R"(\bSTA\b)"  },
    { LDX,          R"(\bLDX\b)"  },
    { STX,          R"(\bSTX\b)"  },
    { LDY,          R"(\bLDY\b)"  },
    { STY,          R"(\bSTY\b)"  },
    { RMB0,         R"(\bRMB0\b)" },
    { RMB1,         R"(\bRMB1\b)" },
    { RMB2,         R"(\bRMB2\b)" },
    { RMB3,         R"(\bRMB3\b)" },
    { RMB4,         R"(\bRMB4\b)" },
    { RMB5,         R"(\bRMB5\b)" },
    { RMB6,         R"(\bRMB6\b)" },
    { RMB7,         R"(\bRMB7\b)" },
    { SMB0,         R"(\bSMB0\b)" },
    { SMB1,         R"(\bSMB1\b)" },
    { SMB2,         R"(\bSMB2\b)" },
    { SMB3,         R"(\bSMB3\b)" },
    { SMB4,         R"(\bSMB4\b)" },
    { SMB5,         R"(\bSMB5\b)" },
    { SMB6,         R"(\bSMB6\b)" },
    { SMB7,         R"(\bSMB7\b)" },
    { STZ,          R"(\bSTZ\b)"  },
    { TSB,          R"(\bTSB\b)"  },
    { TRB,          R"(\bTRB\b)"  },
    { TAX,          R"(\bTAX\b)"  },
    { TXA,          R"(\bTXA\b)"  },
    { TAY,          R"(\bTAY\b)"  },
    { TYA,          R"(\bTYA\b)"  },
    { TSX,          R"(\bTSX\b)"  },
    { TXS,          R"(\bTXS\b)"  },
    { PLA,          R"(\bPLA\b)"  },
    { PHA,          R"(\bPHA\b)"  },
    { PLP,          R"(\bPLP\b)"  },
    { PHP,          R"(\bPHP\b)"  },
    { PHX,          R"(\bPHX\b)"  },
    { PHY,          R"(\bPHY\b)"  },
    { PLX,          R"(\bPLX\b)"  },
    { PLY,          R"(\bPLY\b)"  },
    { BRA,          R"(\bBRA\b)"  },
    { BPL,          R"(\bBPL\b)"  },
    { BMI,          R"(\bBMI\b)"  },
    { BVC,          R"(\bBVC\b)"  },
    { BVS,          R"(\bBVS\b)"  },
    { BCC,          R"(\bBCC\b)"  },
    { BCS,          R"(\bBCS\b)"  },
    { BNE,          R"(\bBNE\b)"  },
    { BEQ,          R"(\bBEQ\b)"  },
    { BBR0,         R"(\bBBR0\b)" },
    { BBR1,         R"(\bBBR1\b)" },
    { BBR2,         R"(\bBBR2\b)" },
    { BBR3,         R"(\bBBR3\b)" },
    { BBR4,         R"(\bBBR4\b)" },
    { BBR5,         R"(\bBBR5\b)" },
    { BBR6,         R"(\bBBR6\b)" },
    { BBR7,         R"(\bBBR7\b)" },
    { BBS0,         R"(\bBBS0\b)" },
    { BBS1,         R"(\bBBS1\b)" },
    { BBS2,         R"(\bBBS2\b)" },
    { BBS3,         R"(\bBBS3\b)" },
    { BBS4,         R"(\bBBS4\b)" },
    { BBS5,         R"(\bBBS5\b)" },
    { BBS6,         R"(\bBBS6\b)" },
    { BBS7,         R"(\bBBS7\b)" },
    { STP,          R"(\bSTP\b)"  },
    { WAI,          R"(\bWAI\b)"  },
    { BRK,          R"(\bBRK\b)"  },
    { RTI,          R"(\bRTI\b)"  },
    { JSR,          R"(\bJSR\b)"  },
    { RTS,          R"(\bRTS\b)"  },
    { JMP,          R"(\bJMP\b)"  },
    { BIT,          R"(\bBIT\b)"  },
    { TRB,          R"(\bTRB\b)"  },
    { TSB,          R"(\bTSB\b)"  },
    { CLC,          R"(\bCLC\b)"  },
    { SEC,          R"(\bSEC\b)"  },
    { CLD,          R"(\bCLD\b)"  },
    { SED,          R"(\bSED\b)"  },
    { CLI,          R"(\bCLI\b)"  },
    { SEI,          R"(\bSEI\b)"  },
    { CLV,          R"(\bCLV\b)"  },
    { NOP,          R"(\bNOP\b)"  },
    { SLO,          R"(\bSLO\b)"  },
    { RLA,          R"(\bRLA\b)"  },
    { SRE,          R"(\bSRE\b)"  },
    { RRA,          R"(\bRRA\b)"  },
    { SAX,          R"(\bSAX\b)"  },
    { LAX,          R"(\bLAX\b)"  },
    { DCP,          R"(\bDCP\b)"  },
    { ISC,          R"(\bISC\b)"  },
    { ANC2,         R"(\bANC2\b)" },
    { ANC,          R"(\bANC\b)"  },
    { ALR,          R"(\bALR\b)"  },
    { ARR,          R"(\bARR\b)"  },
    { XAA,          R"(\bXAA\b)"  },
    { AXS,          R"(\bAXS\b)"  },
    { USBC,         R"(\bUSBC\b)" },
    { AHX,          R"(\bAHX\b)"  },
    { SHY,          R"(\bSHY\b)"  },
    { SHX,          R"(\bSHX\b)"  },
    { TAS,          R"(\bTAS\b)"  },
    { LAS,          R"(\bLAS\b)"  },
    { IFDEF_DIR,    R"(\.ifdef\b)" },
    { IFNDEF_DIR,   R"(\.ifndef\b)" },
    { IF_DIR,       R"(\.if\b)" },
    { ELSE_DIR,     R"(\.else\b)" },
    { ENDIF_DIR,    R"(\.endif\b)" },
    { FILL_DIR,     R"(\.fill\b)" },
    { VAR_DIR,      R"(\.var\b)" },
    { DO_DIR,       R"(\.do\b)" },
    { WHILE_DIR,    R"(\.while\b)" },
    { WEND_DIR,     R"(\.wend\b)" },
    { ORG,          R"(\.ORG\b)" },
    { BYTE,         R"((\.BYTE\b)|(\.BYT\b)|(\.db\b)|(\.TEXT\b))" },
    { WORD,         R"((\.WORD\b)|(\.WRD\b))" },
    { DS,           R"(\.DS\b)" },
    { MACRO_DIR,    R"((\.MACRO\b)|(\.MAC\b))" },
    { INCLUDE,      R"((\.INCLUDE)|(\.INC\b))" },
    { ENDMACRO_DIR, R"((\.ENDM\b)|(\.ENDMACRO\b))" },
    { PRINT_ON,     R"(\.PRINT[ /t]+ON)" },
    { PRINT_OFF,    R"(\.PRINT[ /t]+OFF)" },
    { X,            R"(\bX\b)" },
    { Y,            R"(\bY\b)" },
    { A,            R"(\bA\b)" },
    { SYM,          R"(([A-Za-z_][A-Za-z0-9_]*))" },
    { LOCALSYM,     R"(\@([A-Za-z_][A-Za-z0-9_]*))" },
    { MACRO_PARAM,  R"(\\\d+)" },
    { EOL,          R"(\r?\n)" },
});

// Parser dictionary
std::map<int64_t, std::string> parserDict = {
    { CHAR,         "CHAR"},
    { DECNUM,       "DECNUM"},
    { OCTNUM,       "OCTNUM"},
    { HEXNUM,       "HEXNUM"},
    { BINNUM,       "BINNUM"},
    { BYTE,         "BYTE"},
    { WORD,         "WORD"},
    { PLUS,         "PLUS"},
    { MINUS,        "MINUS"},
    { COMMA,        "COMMA"},
    { COLAN,        "COLAN"},
    { X,            "X"},
    { Y,            "Y"},
    { A,            "A"},
    { POUND,        "POUND"},
    { MUL,          "MUL"},
    { TEXT,         "TEXT"},
    { MOD,          "MOD"},
    { DIV,          "DIV"},
    { BIT_AND,      "BIT_AND"},
    { BIT_OR,       "BIT_OR"},
    { LOGICAL_AND,  "LOGICAL_AND"},
    { LOGICAL_OR,   "LOGICAL_OR"},
    { BIT_XOR,      "BIT_XOR"},
    { SLEFT,        "SHIFT_LEFT"},
    { SRIGHT,       "SHIFT_LEFT" },
    { LPAREN,       "LEFT_PAREN"},
    { RPAREN,       "RIGHT_PAREN"},
    { ONESCOMP,     "ONES_COMP"},
    { AT,           "AT" },
    { WS,           "WHITE_SPACE" },
    { SYM,          "SYM" },
    { LOCALSYM,     "LOCAL_SYM" },
    { COMMENT,      "COMMENT" },
    { EQUAL,        "EQUALS" },
    { ORG,          "ORG" },
    { EOL,          "EOL" },
    { MACRO_DIR,    "MACRO_DEF" },
    { ENDMACRO_DIR, "END_MACRO" },
    { MACRO_PARAM,  "MACRO_PARAM" },
    { INCLUDE,      "INCLUDE"},
    { Factor,       "Factor" },
    { MulExpr,      "MulExpr" },
    { AddExpr,      "AddExpr" },
    { AddrExpr,     "AddrExpr" },
    { OrExpr,       "OrExpr" },
    { XOrExpr,      "XOrExpr" },
    { LogicalAndExpr, "LogicalAndExpr" },
    { LogicalOrExpr,  "LogicalOrExpr" },
    { IfDirective,   "IfDirective" },
    { ShiftExpr,    "ShiftExpr"},
    { MacroDef,     "MacroDef" },
    { MacroStart,   "MacroStart" },
    { MacroCall,    "MacroCall" },
    { MacroArgs,    "MacroArgs" },
    { EndMacro,     "EndMacro" },
    { AndExpr,      "AndExpr" },
    { ExprList,     "ExpressionList" },
    { TextExpr,     "TextExpr" },
    { VarDirective, "Var directive"},
    { VarItem,      "Var Item"},        // Single variable declaration
    { VarList,      "Var List"},        // Comma-separated list of VarItems
    { ORA,      "ORA"  },
    { AND,      "AND"  },
    { EOR,      "EOR"  },
    { ADC,      "ADC"  },
    { SBC,      "SBC"  },
    { CMP,      "CMP"  },
    { CPX,      "CPX"  },
    { CPY,      "CPY"  },
    { DEC,      "DEC"  },
    { DEX,      "DEX"  },
    { DEY,      "DEY"  },
    { INC,      "INC"  },
    { INX,      "INX"  },
    { INY,      "INY"  },
    { ASL,      "ASL"  },
    { ROL,      "ROL"  },
    { LSR,      "LSR"  },
    { ROR,      "ROR"  },
    { LDA,      "LDA"  },
    { STA,      "STA"  },
    { LDX,      "LDX"  },
    { STX,      "STX"  },
    { LDY,      "LDY"  },
    { STY,      "STY"  },
    { RMB0,     "RMB0" },
    { RMB1,     "RMB1" },
    { RMB2,     "RMB2" },
    { RMB3,     "RMB3" },
    { RMB4,     "RMB4" },
    { RMB5,     "RMB5" },
    { RMB6,     "RMB6" },
    { RMB7,     "RMB7" },
    { SMB0,     "SMB0" },
    { SMB1,     "SMB1" },
    { SMB2,     "SMB2" },
    { SMB3,     "SMB3" },
    { SMB4,     "SMB4" },
    { SMB5,     "SMB5" },
    { SMB6,     "SMB6" },
    { SMB7,     "SMB7" },
    { STZ,      "STZ" },
    { TAX,      "TAX" },
    { TXA,      "TXA" },
    { TAY,      "TAY" },
    { TYA,      "TYA" },
    { TSX,      "TSX" },
    { TXS,      "TXS" },
    { PLA,      "PLA" },
    { PHA,      "PHA" },
    { PLP,      "PLP" },
    { PHP,      "PHP" },
    { PHX,      "PHX" },
    { PHY,      "PHY" },
    { PLX,      "PLX" },
    { PLY,      "PLY" },
    { BRA,      "BRA" },
    { BPL,      "BPL" },
    { BMI,      "BMI" },
    { BVC,      "BVC" },
    { BVS,      "BVS" },
    { BCC,      "BCC" },
    { BCS,      "BCS" },
    { BNE,      "BNE" },
    { BEQ,      "BEQ" },
    { BBR0,     "BBR0" },
    { BBR1,     "BBR1" },
    { BBR2,     "BBR2" },
    { BBR3,     "BBR3" },
    { BBR4,     "BBR4" },
    { BBR5,     "BBR5" },
    { BBR6,     "BBR6" },
    { BBR7,     "BBR7" },
    { BBS0,     "BBS0" },
    { BBS1,     "BBS1" },
    { BBS2,     "BBS2" },
    { BBS3,     "BBS3" },
    { BBS4,     "BBS4" },
    { BBS5,     "BBS5" },
    { BBS6,     "BBS6" },
    { BBS7,     "BBS7" },
    { STP,      "STP" },
    { WAI,      "WAI" },
    { BRK,      "BRK" },
    { RTI,      "RTI" },
    { JSR,      "JSR" },
    { RTS,      "RTS" },
    { JMP,      "JMP" },
    { BIT,      "BIT" },
    { TRB,      "TRB" },
    { TSB,      "TSB" },
    { CLC,      "CLC" },
    { SEC,      "SEC" },
    { CLD,      "CLD" },
    { SED,      "SED" },
    { CLI,      "CLI" },
    { SEI,      "SEI" },
    { CLV,      "CLV" },
    { NOP,      "NOP" },
    { SLO,      "SLO" },
    { RLA,      "RLA" },
    { SRE,      "SRE" },
    { RRA,      "RRA" },
    { SAX,      "SAX" },
    { LAX,      "LAX" },
    { DCP,      "DCP" },
    { ISC,      "ISC" },
    { ANC,      "ANC" },
    { ANC2,     "ANC2" },
    { ALR,      "ALR" },
    { ARR,      "ARR" },
    { XAA,      "XAA" },
    { AXS,      "AXS" },
    { USBC,     "USBC" },
    { AHX,      "AHX" },
    { SHY,      "SHY" },
    { SHX,      "SHX" },
    { TAS,      "TAS" },
    { LAS,      "LAS" },
    
    { OpCode,           "OpCode" },
    { Op_Instruction,   "Op_Instruction" },
    { Op_Implied,       "OpCode_Implied" },
    { Op_Accumulator,   "OpCode_Accumulator" },
    { Op_Immediate,     "OpCode_Immediate" },
    { Op_Absolute,      "OpCode_Absolute" },
    { Op_AbsoluteX,     "OpCode_AbsoluteX" },
    { Op_AbsoluteY,     "OpCode_AbsoluteY" },
    { Op_ZeroPage,      "OpCode_ZeroPage" },
    { Op_ZeroPageX,     "OpCode_ZeroPageX" },
    { Op_ZeroPageY,     "OpCode_ZeroPageY" },
    { Op_Indirect,      "OpCode_Indirect" },
    { Op_IndirectX,     "OpCode_IndirectX" },
    { Op_IndirectY,     "OpCode_IndirectY" },

    { Op_Relative,      "OpCode_Relative" },
    { Op_ZeroPageRelative,  "OpCode_ZeroPageRelative"},

    { PRINT_ON,         "print_on" },
    { PRINT_OFF,        "print_off" },
    { IFDEF_DIR,        "ifdef" },
    { IFNDEF_DIR,       "ifndef" },
    { IF_DIR,           "if" },
    { ELSE_DIR,         "else" },
    { ENDIF_DIR,        "endif" },
    { VAR_DIR,          "var" },
    { DO_DIR,           "do" },
    { WHILE_DIR,        "while" },
    { WEND_DIR,         "wend" },
    { DS,               "defineStorage" },
    { LT,               "lessthan" },
    { GT,               "greaterthan" },
    { LE,               "lessthanequal" },
    { GE,               "greaterthanequal" },
    { DEQUAL,           "doubleequals" },
    { NOTEQUAL,         "notequal" },
    { RelExpr,          "RelativeExpression" },
    { EqExpr,           "EqualExpresson" },
    { Number,           "Number" },
    { SymbolRef,        "SymbolRef" },
    { LabelDef,         "LabelDef" },
    { SymbolName,       "SymbolName"},
    { Equate,           "Equate" },
    { Expr,             "Expr" },
    { PlusRun,          "PlusRun" },
    { MinusRun,         "MinusRun" },
    { AnonLabelRef,     "AnonLabelRef" },
    { OrgDirective,     "OrgDirective" },
    { ByteDirective,    "ByteDirective" },
    { WordDirective,    "WordDirective" },
    { StorageDirective, "StoreageDirective"},
    { IncludeDirective, "IncludeDirective" },
    { DoDirective,      "DoDirective" },
    { WhileDirective,   "WhileDirective" },
    { PrintDirective,   "PrintDirective" },
    { Comment,          "Comment" },
    { Statement,        "Statement" },
    { Line,             "Line" },
    { LineList,         "LineList" },
    { EOLOrComment,     "EOLorComment" },
    { FILL_DIR,         "FILL_DIR" },
    { PCAssign,         "PCAssign"},
    { FillDirective,    "FillDirective"},
    { TokenNode,        "TokenNode" },
    { Prog,             "Prog" },
};
